### ISSUE TITLE
When clicking Toolbar icon, show the last search results

### ISSUE THREAD

**Issue by MKaveh** [reblws/tab-search#12]
The search query and results is reset whenever clicking on toolbar button, which makes it inconvenient to view the matched tabs having to enter search query again.

**Comment by reblws** [comment]
I'll add this as an option in the next release (0.3.4).

**Comment by reblws** [comment]
You can now do this by ticking 'Show the last query's results when opening the popup window' under the Search Results section of the settings. Let me know if you have any problems with the feature or the wording of the setting.
