### ISSUE TITLE
Expose history to extension

### ISSUE THREAD

**Issue by blakebutcher** [reblws/tab-search#19]
In TabSearch settings there is the "Show recently closed tabs - Limit (max. 25):" option. I'd really like to have more than 25.

Is this limit there for performance reasons or something else?

**Comment by reblws** [comment]
It's [hardcoded](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/sessions/MAX_SESSION_RESULTS) unfortunately.

**Comment by reblws** [comment]
Can get around this by storing the last `n` recently closed tabs by recording all tabs closed, but that seems like an invasion of privacy.

**Comment by blakebutcher** [comment]
Would exposing the entire history be possible? https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/history/search

**Comment by reblws** [comment]
Yeah, why not.
