### ISSUE TITLE
Expose Bookmarks via TabSearch

### ISSUE THREAD

**Issue by blakebutcher** [reblws/tab-search#20]
If the tab I'm looking for isn't there, but I have bookmarked it, it would be great if that appeared in the TabSearch results. Similar to how recently closed tabs can appear.

**Comment by reblws** [comment]
I was originally gonna put this in 0.3.0 but I felt like it was a bit too out of scope. But since it's been suggested multiple times I'll give it a shot again. My main concern is that I don't want the bookmarks to clutter the results up too much. 

I think a nice way to do this without overhauling the UI too much (I'd eventually like to make your vertical overlay idea the main UI in the future) would be to only show bookmarks if no tabs are found or if a special keyword is included in the search query (maybe `!b`) -- what do you think?

**Comment by blakebutcher** [comment]
Having the bookmarks cluttering up the results isn't something I'm too concerned about. I'd be happy for the matching bookmarks to be grouped together (with a 3rd colour indicator strip) either before or after the recently closed tabs.

If that does end up being too cluttered perhaps you could add a preference for only showing them when no open tabs are found (along with the keyword for overriding that behaviour). If it was a preference I doubt I would have it enabled.

**Comment by reblws** [comment]
Hi, here's how the bookmarks look now. The bookmarks API doesn't expose the favicon url so in the meantime I've placed a bookmark SVG as a placeholder. I actually think it looks nicer with the svg, and makes it more clear that it's a bookmark.

I'm not sure about the color though, it's not distinctive enough from the blue of current-window tabs. Will probably change it.

![wishes](https://user-images.githubusercontent.com/9971847/33225467-2810b61a-d146-11e7-94e6-53a7c2408db2.png)

When the hover style is applied, visiblity of the SVG is hampered:

![wishes-highlighted](https://user-images.githubusercontent.com/9971847/33225466-25c16aee-d146-11e7-8682-620706b90a95.png)

Can get around the visibility problem under selection by: 
- Inlining the SVG and conditionally filling it with a different color, or
- Change the primary bookmark color so it's more visible under selection

I still need to write a new setting that pushes tabs to the bottom (but above recently closed). I am not a big fan of bookmarks getting in the way.

**Comment by Rictusempra** [comment]
Hey, gotta suggestion here:
why not use multi-column view:
three columns, one for opened tabs, one for bookmarks and the rest for history.
Simply put ticket boxes at the top so that users can get rid of a column s/he does not want.

**Comment by reblws** [comment]
Hey @Rictusempra, thanks for the suggestion. Right now I'm focusing on getting a good core set of features developed first before overhauling the visuals. I plan on exploring a multi-column view in #5 after the next feature patch is done (0.4.0).
