### ISSUE TITLE
Custom keyboard navigation shortcuts

### ISSUE THREAD

**Issue by reblws** [reblws/tab-search#22]
By request:

Should be able to customize navigation shortcuts, which are:
- Delete a tab
- Open selected tab
- Select next tab
- Select previous tab

Should start by refactoring string literals in https://github.com/reblws/tab-search/blob/master/src/core/pages/popup/event-callbacks.js#L41

**Comment by oux** [comment]
Unfortunately the CTRL+Shift+F is in conflict with [sidebar Tab](https://addons.mozilla.org/fr/firefox/addon/tab-sidebar-we/)

**Comment by tsdh** [comment]
I'd also very much like to use a different shortcut than the standard `Ctrl+Shift+F` to fire up the tab list.

**Comment by reblws** [comment]
Sorry @oux, @tsdh there's nothing I can do about the default popup shortcut until Firefox implements custom shortcuts for extensions. See #2
