### ISSUE TITLE
Layout bug with long non-breaking strings in page titles

### ISSUE THREAD

**Issue by blakebutcher** [reblws/tab-search#23]
![title-bug](https://user-images.githubusercontent.com/245146/32863564-08d08a1a-cab0-11e7-85f0-191e99563e25.png)

Could this be fixed using `word-break: break-all`?

**Comment by reblws** [comment]
Cool it does, thanks.

![scrn](https://user-images.githubusercontent.com/9971847/32866186-5402f2d8-ca34-11e7-8a79-8501a9938481.png)
