### ISSUE TITLE
Option to display tabs in popup by MRU

### ISSUE THREAD

**Issue by sinewave** [reblws/tab-search#36]
Just discovered this addon and it's awesome!! Thx!

One feature i would really love to see is the ability to order the tabs in the popup by most recently used. I usually have a ton of tabs open so listing tabs by MRU would allow me to quickly jump to a tab i was recently if i don't remember the name of it or don't feel like searching.

Check out https://github.com/babyman/quick-tabs-chrome-extension for a great Chrome plugin that does this.

**Comment by reblws** [comment]
Hi, glad you like the extension. This is a good idea.

Shouldn't be too much of a problem adding this. Is it important for the search results to be ordered this way as well? I'm going to just do this for the initial popup, and not sort the search results for now.

**Comment by sinewave** [comment]
Hey, thx for the quick response.... and can't wait to start using this feature 💯 

Regarding your question... yea, i think when searching results should be ordered by relevance 👍

**Comment by reblws** [comment]
Should be up tonight, let me know if there are any issues.
