### ISSUE TITLE
suggestions: to truncate tab names to just 1 line and more

### ISSUE THREAD

**Issue by berlihingen** [reblws/tab-search#40]
- ability to truncate tab name to 1 line (coz some outdated SEOs writes long paragraphs here which takes a lot of space);
- ability to choose between colored sidelines (if anyone prefers) and greyed background for Recently Closed
- ability to change the background color of Number of tabs small icon (again, grey is preferable as Quantum basic design choice)
Thanks.

**Comment by reblws** [comment]
Thanks! I'll look into implementing these.

**Comment by reblws** [comment]
Alright looks like most of these are complete as of 0.4.4. If you have any issues with the way they're implemented, let me know and I'll re-open this.
