### ISSUE TITLE
Search text not cleared after popup dismissed

### ISSUE THREAD

**Issue by sinewave** [reblws/tab-search#43]
Hi,

Awesome plugin!!! I'm having an issue though when searching... I would assume that my search text would be cleared out after the popup is dismissed however it seems to persist which makes repeated searches annoying as i have to remember to always first clear the search text.

Is there a way to reset it automatically?

Thanks

**Comment by reblws** [comment]
Check settings under "Behavior" and make sure "Show the last query's results when opening the popup window". Let me know if that doesn't work.

**Comment by sinewave** [comment]
Whoops...that was it! Thx
