### ISSUE TITLE
Support binding more than one keyboard shortcut to an action.

### ISSUE THREAD

**Issue by thomcc** [reblws/tab-search#49]
At least for the actions that take effect when the panel is open (e.g. this is unrelated to #2). There are a number of reasons someone might want to do this, but personally:

On macOS, in most menus (all/almost all native menus, at least), as well as almost all text boxes you can navigate up and down a line using either the arrow keys, *or* `Ctrl+N` and `Ctrl+P`. For clarity, I actually mean the control key, `MacCtrl`, *not* `Cmd`. (Strangely, macOS supports a number of other similar movement options inherited from emacs, of all places. Regardless, some people like myself come to use them heavily).

This is in addition to allowing arrow keys (which I also use).

In your extension I'd like to be able to navigate with *either* arrow keys *or* `Ctrl+N`/`Ctrl+P`, but as it is, I need to choose.

Instead of asking for your extension to code in this macOS quirk, it would probably be better to just support allowing multiple shortcuts for a single action.

**Comment by reblws** [comment]
Thanks, had a feeling that would be an issue. It'll be out in the next update.

**Comment by reblws** [comment]
@thomcc I don't have a Mac on-hand to test this properly, but does setting a shortcut with `MacCtrl` work as intended and is it treated differently from `Cmd`?

**Comment by thomcc** [comment]
I can't actually get it to store a `MacCtrl` in the key shortcut. If I try to type control + N, it stores it as `Cmd+N`. However, it then accepts either `Ctrl+N` or `Cmd+N`. Or it would, if `Cmd+N` weren't already "open new window" (it works as I describe if I find a key binding that isn't used by Firefox for something else, like `Cmd+Y`).

I planned on reporting this, but fixing it could be workflow breaking without migrating mac users who have `` `Cmd+${key}` `` bound to have both ``[`Cmd+${key}`, `MacCtrl+${key}`]``. (Which, of course, requires fixing this bug first so that multiple key bindings for the same action are supported).

Anyway, this is an entirely separate issue. I *can* rebind it to make control + N / P work, but the issue is that I would like to have that work, as well as the arrow keys, e.g. more than one key binding for the same action.
