### ISSUE TITLE
Cannot find Keyboard shortcut doc ?

### ISSUE THREAD

**Issue by Kuranes** [reblws/tab-search#54]
How do we popup the tabsearch ?
(for instance chrome tab search is "ctrl+i"  and it's clearly shown in the addon page https://chrome.google.com/webstore/detail/tab-search/mgfejaiakfkkipbelelkcfbimnfjhebn )

**Comment by reblws** [comment]
Note that the shortcut doesn't work unless the popup icon is visible in
your browser toolbars.

On Wed, Mar 7, 2018 at 2:13 PM, Enrico Baculinao <enrico.baculinao@gmail.com
> wrote:

> If you're on macOS:
> Cmd+Shift+L
>
> If on Windows/Linux:
> Ctrl+Shift+F
>
> The search input placeholder text should display the activation shortcut.
> It should read: "Search for a tab (<SHORTCUT> opens this)"
>
> If it doesn't appear like that for you, let me know and I'll file this as
> a bug.
>

**Comment by reblws** [comment]
If you're on macOS:
Cmd+Shift+L

If on Windows/Linux:
Ctrl+Shift+F

The search input placeholder text should display the activation shortcut.
It should read: "Search for a tab (<SHORTCUT> opens this)"

If it doesn't appear like that for you, let me know and I'll file this as a
bug.

**Comment by Kuranes** [comment]
Thanks for the fast answer, it works.
Have it in the place holder, stange I didn't notice earlier.
Great work !
