### ISSUE TITLE
Improve keyboard navigation

### ISSUE THREAD

**Issue by drtebi** [reblws/tab-search#56]
This is a very nice add-on, I just wish a couple of keyboard actions could be improved:

- When I use the up-arrow to go through the list and reach the search box, another up-arrow key press should go to the bottom of the tab list (the last item). There is no use for the up-arrow in the search box anyway, so I believe this is worth the effort. That way one can easily navigate the list backwards.
- The end-key scrolls the list to the bottom, but doesn't change the selection. In my opinion, it should also select the last item in the list.
- The same applies to the home-key
- The page-up and page-down key scroll the list, but don't change the selection. In most applications (e.g. your file browser), the selection would also change.
- Shift-tab should go backwards in the list (this is already filed in another issue).

These are just my improvement suggestions. The add-on itself is already very good, a bit of polishing of the keyboard navigation would make it perfect :)

**Comment by reblws** [comment]
Hey @drtebi, thanks for your feedback, I've implemented most of your suggestions. 

The only one I'm not sure about is one aspect of the Home/End changes. 

Right now the way I have it set up is if either of those keys are pressed, the focus jumps to the end of the tab list regardless of whether the search input is active or not, but Home/End keys are also used to jump to the end of a line.

If the search input is active I'm thinking maybe it shouldn't skip to the end of the tablist, but should jump the cursor to the end of the search input instead.

Curious to hear your thoughts on this.

**Comment by ciufudean** [comment]
+1 for "no mouse"
what I am missing is the ability to ctrl+shift+f and then start typing in the search box
I am looking to switch to FF - I am using Quick Tabs in Chrome

**Comment by ciufudean** [comment]
Nope, it is the first time I've installed the extension

**Comment by reblws** [comment]
Ah ok @ciufudean, it should be fixed by Firefox 60. In the meantime, try pressing <kbd>Tab</kbd> as soon as you open the popup window. That should focus the search input immediately.
