### ISSUE TITLE
Ability to change searchbox backround color

### ISSUE THREAD

**Issue by azzamsa** [reblws/tab-search#65]
Hi.

I didn't believe this extension exist. It's really cool.

Can we have the ability to change search box background color ?

![coba](https://user-images.githubusercontent.com/17734314/45730833-3cbe6c80-bbfe-11e8-8da7-99cb2f74c81a.png)

Thank you for tab-search. :)

**Comment by AndydeCleyre** [comment]
Is there a setting for this? I can't find it. I'm just trying this addon for the first time, but I have no way of clearly seeing what's typed there.

**Comment by azzamsa** [comment]
Now Firefox let's you search active tabs using `% tabname`
