### ISSUE TITLE
Change main Keyboard Shortcut

### ISSUE THREAD

**Issue by obriat** [reblws/tab-search#67]
Ctrl + shift + F overlaps "Panorama view" extension own shortcut.

It should be possible to change it in the extension settings page, that also a good place to to learn it, since this info is only available on the extension web page.

**Comment by tolgacanatan** [comment]
It is really hard to press 'ctrl + shift + f'. We should be able to change this shortcut.

**Comment by tg-x** [comment]
this is a duplicate of #2
