### ISSUE TITLE
Questions about "History in search results"

### ISSUE THREAD

**Issue by LL25255252** [reblws/tab-search#89]
1. Does the addon use firefox place.sqlite or does it use its own file ?
2. If the addon uses its own file what's the mechanism that keep this file from getting too big ?
Thanks in advance.

**Comment by reblws** [comment]
Hi the addon does not use its own file, it uses the [WebExtensions History API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/history) provided by Firefox.

When the history shows up in your list it is kept in memory and not stored anywhere.
