### ISSUE TITLE
Does not show any tabs anymore

### ISSUE THREAD

**Issue by TheBlackEntity** [reblws/tab-search#91]
Already experiencing this for a few days...

If I click on the TabSearch icon, only a blank screen with search bar appears.

It seems to know about a few tabs, the icon has a number on it.

Clicking on the blank screen does nothing

**Comment by reblws** [comment]
Hi that sounds concerning. Can you share some more information about your system?

What OS are you running? What version of Firefox? Do you have many other extensions installed?

**Comment by TheBlackEntity** [comment]
> Hi that sounds concerning. Can you share some more information about your system?
> 
> What OS are you running? What version of Firefox? Do you have many other extensions installed?

Hey,
I'm using ArcoLinux as my OS.
I'm also using the Firefox fork "Waterfox", because that one seems to fix a massive glitch I had with normal Firefox.

Yes, I do have many extensions installed, but didn't install any new extensions before this issue occured

**Comment by iSplasher** [comment]
I'm experiencing the same thing on Windows 11, Firefox 99.0.1

**Comment by reblws** [comment]
That's great to hear @iSplasher thanks for confirming that. I haven't been able to reproduce it myself but that sounds like the only thing that could cause this. 

Closing this issue.
